[options]
HoldPkg     = pacman glibc
Architecture = aarch64
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[forge]
Server = https://arch-linux-repo.drzee.net/arch/$repo/os/$arch

[core]
Server = https://arch-linux-repo.drzee.net/arch/$repo/os/$arch

[extra]
Server = https://arch-linux-repo.drzee.net/arch/$repo/os/$arch

[aarch64-addons]
Server = https://github.com/archlinux-aarch64-test-pkgs/.repo-db/releases/download/latest
SigLevel = Never
